name: Test-pipeline-dev
env:
  SHA: ${{ github.sha }}
  BRANCH: ${{ github.ref_name }}

on:
  push:
    branches:
    - dev
    - staging
    paths:
    - 'README*'
  pull_request:
    branches:
    - dev
    - staging
    paths:
    - 'README*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Echo SHA and branch
      run: |
        echo $SHA
        echo ${{ env.BRANCH }}

    - name: Echo Branch push
      if: github.event_name == 'push'
      env:
        MY_BRANCH: ${{ env.BRANCH }}
      run: |
        echo "Branch: $MY_BRANCH"
        echo "Action: ${{ github.event_name }}"

    - name: Echo Branch pr
      if: github.event_name == 'pull_request'
      env:
        MY_BRANCH: ${{ env.BRANCH }}
      run: |
        echo "Action: ${{ github.event_name }}"
        echo "From: ${{ github.head_ref }}"
        echo "Full ref: ${{ github.ref }}"
        echo "To: ${{ github.base_ref }}"

